### ISSUE TITLE
[tutorials/tensorflow/mobilenet-v1-1.0-224-tf/]

### ISSUE THREAD

**Issue by agnyde** [Microchip-Vectorblox/VectorBlox-SDK#6]
Hi, my set up is a VM **Ubuntu 20.04x64** (kernel 5.13.0-28-generic). VirtualBox version is 6.1.32.   
I try to run some tutorials in vbx environment, but I always have the same error. I followed the guide instructions, I run install_dependencies.sh and source setup_vars.sh and then in the tutorial folder I try to run **mobilenet-v1-1.0-224-tf.sh**  and I have these two warnings and the **core dumped** error:  
![immagine](https://user-images.githubusercontent.com/99801735/154249678-471b0237-7f55-403a-9b84-38076f4bfd04.png)
So no results are generated, what could be the problem? Best regard

**Comment by LiiNen** [comment]
It seems like dependencies are not successfully installed

Is there a file named 'converter' in path below?
{your working directory}/VectorBlox-SDK/vbx_env/bin/converter

if the converter file not exists, consider installing the dependencies again

best regard,

**Comment by cirqueit** [comment]
This should be simplified in release 1.3 (coming out this week). We will be using openvino-dev which provides mo (previously converter) and omz_downloader (previously downloader).

Please try 1.3 when released, and confirm it works in your VM.

**Comment by cirqueit** [comment]
This is likely due to tensorflow not being able to run on your machine (often due to AVX instructions?). 
You may need to build tensorflow from source.

Run `python -c "import tensorflow"` to see if thats your issue

**Comment by LiiNen** [comment]
@agnyde Hi, sorry for late response of your mention.

I'm not sure about your problem, so VectorBlox developers might know.
One thing I can advise you is using the previous version.
Although the problems were not same, I also had trouble when I testing the board.
When I use the previous version of source code, that problems were solved.

The commit hash which I used is below:
[30b9c2815dae7c098e057a57c2656809d3ded03e](url)

If you struggle yet, how about trying the previous version?
This may not be the solution, but I think it worth it.
Best regards,

**Comment by agnyde** [comment]
Hello, thanks for your answers. 
@LiiNen tensorflow core-dumped problem persists in all versions of source code. 
@cirqueit as you correctly pointed out the problem is the import of tensorflow, because AVX instructions are not supported on my machine. I tried to build tensorflow from source following this tutorial:
https://gist.github.com/kmhofmann/e368a2ebba05f807fa1a90b3bf9a1e03
without success. 
So at the moment it seems that tensorflow cannot be used on **vbx_enx** if AVX istructions are not supported.
Do you have any other suggestions? 
Thanks

**Comment by cirqueit** [comment]
Tensorflow is required when converting TF graphs into OpenVINO. If TF graphs are important, I would either stay trying to get a version of tensorflow built and installed in your env or enable AVX instructions in your virtual box VM as discussed 
[here](https://stackoverflow.com/questions/65780506/how-to-enable-avx-avx2-in-virtualbox-6-1-16-with-ubuntu-20-04-64bit)

The rest of the flow does not use TF.
